// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Viem from "viem";
import * as Edgedb from "edgedb";
import * as Constants from "@my/schema/src/Constants.mjs";
import * as Nodehttp from "node:http";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as DataLoaders from "@my/schema/src/DataLoaders.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as GraphqlYoga from "graphql-yoga";
import * as ResGraphSchema from "@my/schema/__generated__/ResGraphSchema.mjs";

var edgedbClient = Edgedb.createClient();

var viemClient = Viem.createPublicClient({
      chain: Constants.chain,
      transport: Viem.http(Constants.transportUrl)
    });

var $$default = GraphqlYoga.createYoga({
      schema: ResGraphSchema.schema,
      context: (async function (param) {
          return {
                  sendpayKey: Core__Option.getOr(Caml_option.nullable_to_opt(param.request.headers.get("x-sendpay-key")), ""),
                  dataLoaders: DataLoaders.make(edgedbClient),
                  edgedbClient: edgedbClient,
                  viemClient: viemClient
                };
        }),
      graphqlEndpoint: "/api/graphql"
    });

if (Core__Option.isNone(process.env.VERCEL_ENV)) {
  var yoga = GraphqlYoga.createYoga({
        schema: ResGraphSchema.schema,
        context: (async function (param) {
            return {
                    sendpayKey: Core__Option.getOr(Caml_option.nullable_to_opt(param.request.headers.get("x-sendpay-key")), ""),
                    dataLoaders: DataLoaders.make(edgedbClient),
                    edgedbClient: edgedbClient,
                    viemClient: viemClient
                  };
          }),
        graphqlEndpoint: "/api/graphql"
      });
  var server = Nodehttp.createServer(yoga);
  server.listen(9000, (function () {
          console.info("Server is running on http://localhost:9000/api/graphql");
        }));
}

export {
  edgedbClient ,
  viemClient ,
  $$default as default,
}
/* edgedbClient Not a pure module */
