// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TodoDataLoaders from "./TodoDataLoaders.mjs";
import * as UserDataLoaders from "./UserDataLoaders.mjs";

function make() {
  return {
          user: UserDataLoaders.make(),
          todo: TodoDataLoaders.make()
        };
}

export {
  make ,
}
/* TodoDataLoaders Not a pure module */
