// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DataLoader from "resgraph/src/res/DataLoader.mjs";
import * as GraphqlRelayConnectionsMjs from "resgraph/src/res/graphqlRelayConnections.mjs";

async function listTodos(param, ctx, filterText, completed, first, after, before, last) {
  var todos = await DataLoader.load(ctx.dataLoaders.todo.list, {
        completed: completed,
        filterText: filterText
      });
  return GraphqlRelayConnectionsMjs.connectionFromArray(todos, {
              after: after,
              first: first,
              before: before,
              last: last
            });
}

export {
  listTodos ,
}
/* DataLoader Not a pure module */
