// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PretendDb from "./PretendDb.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";
import * as NodeInterfaceResolver from "./NodeInterfaceResolver.mjs";

async function todoUpdate(param, input, ctx) {
  var todoId = NodeInterfaceResolver.dbIdForType(input.todoId, "Todo");
  var match = ctx.currentUserId;
  if (todoId === undefined) {
    return {
            TAG: "Error",
            message: "Invalid todo id."
          };
  }
  if (match === undefined) {
    return {
            TAG: "Error",
            message: "You need to be logged in to update todo's."
          };
  }
  var newTodo = await PretendDb.updateTodo(todoId, (function (todo) {
          return {
                  id: todo.id,
                  text: Core__Option.getOr(input.text, todo.text),
                  completed: Core__Option.getOr(input.completed, todo.completed)
                };
        }));
  if (newTodo.TAG === "Ok") {
    return {
            TAG: "Ok",
            updatedTodo: newTodo._0
          };
  } else {
    return {
            TAG: "Error",
            message: newTodo._0
          };
  }
}

async function todoDelete(param, todoId) {
  var todoDbId = NodeInterfaceResolver.dbIdForType(todoId, "Todo");
  if (todoDbId === undefined) {
    return {
            TAG: "Error",
            reason: "Invalid ID for Todo."
          };
  }
  var msg = await PretendDb.deleteTodo(todoDbId);
  if (msg.TAG === "Ok") {
    return {
            TAG: "Ok",
            deletedTodoId: todoId
          };
  } else {
    return {
            TAG: "Error",
            reason: msg._0
          };
  }
}

async function todoAdd(param, input) {
  var addedTodo = await PretendDb.addTodo(input.text, input.completed);
  if (addedTodo.TAG === "Ok") {
    return {
            TAG: "Ok",
            addedTodo: addedTodo._0
          };
  } else {
    return {
            TAG: "Error",
            reason: "Could not add Todo."
          };
  }
}

export {
  todoUpdate ,
  todoDelete ,
  todoAdd ,
}
/* NodeInterfaceResolver Not a pure module */
