// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PretendDb from "./PretendDb.mjs";
import * as DataLoader from "resgraph/src/res/DataLoader.mjs";

function make() {
  return {
          byId: DataLoader.makeBatched((async function (todoIds) {
                  var todos = await PretendDb.findManyTodos(todoIds);
                  return todos.map(function (todo) {
                              return todo;
                            });
                }), undefined),
          list: DataLoader.makeSingle((async function (param) {
                  var filteredTodos = await PretendDb.findTodos(param.filterText, param.completed);
                  return filteredTodos.map(function (todo) {
                              return todo;
                            });
                }), undefined)
        };
}

export {
  make ,
}
/* DataLoader Not a pure module */
