// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DataLoader from "resgraph/src/res/DataLoader.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.mjs";

async function me(param, ctx) {
  var userId = ctx.currentUserId;
  if (userId === undefined) {
    return RescriptCore.panic("No logged in user.");
  }
  var user = await DataLoader.load(ctx.dataLoaders.user.byId, userId);
  if (user !== undefined) {
    return user;
  } else {
    return RescriptCore.panic("Did not find logged in user.");
  }
}

export {
  me ,
}
/* DataLoader Not a pure module */
