// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PretendDb from "./PretendDb.mjs";
import * as DataLoader from "resgraph/src/res/DataLoader.mjs";

function make() {
  return {
          byId: DataLoader.makeSingle((async function (userId) {
                  var user = await PretendDb.findSingleUser(userId);
                  if (user !== undefined) {
                    return user;
                  }
                  
                }), undefined)
        };
}

export {
  make ,
}
/* DataLoader Not a pure module */
