// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Viem from "viem";
import * as Edgedb from "edgedb";
import * as Constants from "../src/Constants.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as DataLoaders from "../schema/DataLoaders.mjs";
import * as GraphqlYoga from "graphql-yoga";
import * as ResGraphSchema from "../schema/__generated__/ResGraphSchema.mjs";

var edgedbClient = Edgedb.createClient();

var viemClient = Viem.createPublicClient({
      chain: Constants.chain,
      transport: Viem.http(Constants.transportUrl)
    });

var $$default = GraphqlYoga.createYoga({
      schema: ResGraphSchema.schema,
      context: (async function (param) {
          return {
                  currentUserId: Caml_option.nullable_to_opt(param.request.headers.get("x-user-id")),
                  sendpayKey: "sXGTOzTB4_t9pfuq8tAKCj30X3ZlCVmt6lCQStqrgEo",
                  dataLoaders: DataLoaders.make(),
                  edgedbClient: edgedbClient,
                  viemClient: viemClient
                };
        }),
      graphqlEndpoint: "/api/graphql"
    });

export {
  edgedbClient ,
  viemClient ,
  $$default as default,
}
/* edgedbClient Not a pure module */
