// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as DataLoaders from "../schema/DataLoaders.mjs";
import * as GraphqlYoga from "graphql-yoga";
import * as ResGraphSchema from "../schema/__generated__/ResGraphSchema.mjs";

var $$default = GraphqlYoga.createYoga({
      schema: ResGraphSchema.schema,
      context: (async function (param) {
          return {
                  currentUserId: Caml_option.nullable_to_opt(param.request.headers.get("x-user-id")),
                  dataLoaders: DataLoaders.make()
                };
        }),
      graphqlEndpoint: "/api/graphql"
    });

export {
  $$default as default,
}
/* default Not a pure module */
